plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

// Load GitHub properties file
def githubProperties = new Properties()
githubProperties.load(new FileInputStream(rootProject.file("github.properties")))

/** Function to retrieve version name
 * First part is the base version from toni-kustiana/tracker
 * Second part is this library's version
 */
def getVersionName = { ->
    return "2.3.21-0.0.14"
}

// Function to retrieve artifact ID
def getMyArtifactId = { ->
    return "tracker"
}

afterEvaluate {
    publishing {
        publications {
            bar(MavenPublication) {
                from components.release

                groupId = "id.co.edtslib"
                artifactId = getMyArtifactId()
                version = getVersionName()

                pom {
                    name = getMyArtifactId()
                    description = 'Tracker Library - See CHANGELOG.md for version history'
                    url = 'https://github.com/Dhanfinix/tracker'
                }
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/Dhanfinix/tracker")

                credentials {
                    username = githubProperties['USER_ID'] ?: System.getenv("USER_ID")
                    password = githubProperties['ACCESS_TOKEN'] ?: System.getenv("ACCESS_TOKEN")
                }
            }
        }
    }
}

android {
    namespace 'id.co.edtslib.tracker'
    compileSdk 36

    defaultConfig {
        minSdk 24
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        buildConfigField("String", "DB_PASS", "\"${db_pass_phrase}\"")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        buildConfig = true
        compose = true
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()      // Users can "Go to Definition" in their IDE
            withJavadocJar()      // Better documentation support
        }
    }
}

dependencies {
    api 'androidx.core:core-ktx:1.17.0'
    api 'androidx.appcompat:appcompat:1.7.1'
    api 'com.google.android.material:material:1.13.0'
    api "androidx.preference:preference-ktx:1.2.1"

    // Hilt
    implementation "com.google.dagger:hilt-android:2.57.1"
    ksp "com.google.dagger:hilt-compiler:2.57.1"

    // Lifecycle
    api "androidx.lifecycle:lifecycle-livedata-ktx:2.9.4"
    api "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.4"

    // Networking
    api "com.squareup.retrofit2:retrofit:3.0.0"
    api "com.squareup.retrofit2:converter-gson:3.0.0"
    api "com.squareup.okhttp3:okhttp:5.3.0"
    api "com.squareup.okhttp3:logging-interceptor:5.3.0"
    api "com.facebook.stetho:stetho:1.6.0"
    api "com.facebook.stetho:stetho-okhttp3:1.6.0"

    /* Security */
    api "androidx.security:security-crypto-ktx:1.1.0" // Deprecated
    api "com.scottyab:secure-preferences-lib:0.1.7" // Archived

    /* Coroutines */
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"

    api "com.android.installreferrer:installreferrer:2.2"

    api("com.github.edtslib:baserecyclerview2:1.1.0")
    api("com.github.edtslib:baserecyclerview:1.2.0")

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    /* compose */
    def composeBom = platform("androidx.compose:compose-bom:2025.10.01")
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'
}